# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  peoplewebapp:
    image: peoplewebapp
    build:
      context: .
      dockerfile: People.WebApp/Dockerfile
    ports:
      - 5000:5000
  tests:
    image: mcr.microsoft.com/dotnet/sdk:8.0
    volumes:
      - .:/code
    command:      
      - /bin/bash
      - /code/People.Tests/run.sh